services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  client:
    build: ./client
    ports:
      - "3001:3001"
    depends_on:
      - server

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SPARROW
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
