services:
  server:
    build: ./server
    ports:
      - "3000:3003"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      EXPRESS_SESSION_SECRET: ${EXPRESS_SESSION_SECRET}

  client:
    build: ./client
    ports:
      - "5173:3004"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    # ports:
    #   - "5432:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    # ports:
    #   - "6379:6380"

volumes:
  pgdata:
