services:
  server:
    build: ./server
    ports:
      - "3003:3000" 
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      EXPRESS_SESSION_SECRET: ${EXPRESS_SESSION_SECRET}

  client:
    build: ./client
    ports:
      - "3004:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    # ports:
    #   - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    # ports:
    #   - "6380:6379"

volumes:
  pgdata:
